### ISSUE TITLE
Matching Templets for IRR, other populations

### ISSUE THREAD

**Issue by jessekling** [KyleLuoma/f2s_project#48]
TABDB-R Soldiers in the following CUROGs need to be mapped to the corresponding AOS hierarchy.  These should all be templets and exist under HRC. 

CURORG = DEFAULT UIC

TRDL - R3 Core
8 - W0CQ08

IRR - R3 Core
K - W0CQ0K
L - W0CQ0L
M - W0CQ0M

Standby Reserve - R3 Core
O - W0CQ0N
P - W0CQ0P

Retired - not required but UICs Exist
R - W0CQ0R
6 - W0CQ06
7 - W0CQ07
9 - W0CQ09

More analysis required, they exist in DRRS-A but might be handled by the CCIM, USMA F2S
S - W0CQ0S - RA Dep - This will be loaded from ARRISS but will allow us to estimate templets
T - W0CQ0T - ROTC 
U - W0CQ0U - USMA

Not Required:
A - W0CQAA - National Guard Army
V - W0CQ0V - USAR DEP

**Comment by KyleLuoma** [comment]
While this is a necessary action, I don't believe we need to include it in the F2S program. Because we know that each CURORG belongs in a specific UIC, and those UICs all contain templets, we don't need any sort of matching algorithm. This would be as simple as copying / pasting all of the SSNs into a file with all of the templet FMIDs from a billet extract. Including this volume of data in the F2S program will slow things down pretty significantly.

**Comment by KyleLuoma** [comment]
Have confirmed that SI will handle "singular UIC" populations.
